version: '3'
services:

  connectors:
    build:
      dockerfile: Dockerfile
    container_name: connectors
    environment:
      zeebe.client.cloud.cluster-id: ${cluster_id}
      zeebe.client.cloud.client-id: ${client_id}
      zeebe.client.cloud.client-secret: ${client_secret}
      zeebe.client.cloud.region: ${region}
      CONNECTOR_UploadToAlfresco_FUNCTION: ${CONNECTOR_UploadToAlfresco_FUNCTION}
      CONNECTOR_UploadToAlfresco_TYPE: ${CONNECTOR_UploadToAlfresco_TYPE}
      alfresco.repository.url: ${alfresco_url}
      alfresco.repository.user: ${alfresco_user}
      alfresco.repository.pass: ${alfresco_pass}
    networks:
      - mybridge
    command: ["java", "-jar", "connector.jar"]


networks:
  mybridge:
    driver: bridge

